vim.api.nvim_set_var('mapleader','\\')
vim.api.nvim_set_keymap('n', 'j', 'gj', { noremap = true})
vim.api.nvim_set_keymap('n', 'k', 'gk', { noremap = true })
vim.api.nvim_set_keymap('n', 'j', 'gj', { noremap = true })
vim.api.nvim_set_keymap('n', 'H', '^', { noremap = true })
vim.api.nvim_set_keymap('n', 'L', '$', { noremap = true })
vim.api.nvim_set_keymap('n', 'u', 'g-', { noremap = true })
vim.api.nvim_set_keymap('n', '<C-R>', 'g+', { noremap = true })
vim.api.nvim_set_keymap('n', 'Y', 'y$', { noremap = true })
vim.api.nvim_set_keymap('n', 'x', '"_x', { noremap = true })
vim.api.nvim_set_keymap('n', 'n', 'nzz', { noremap = true })
vim.api.nvim_set_keymap('n', 'N', 'Nzz', { noremap = true })
vim.api.nvim_set_keymap('n', '<C-p>', '<UP>', { noremap = true })
vim.api.nvim_set_keymap('n', '[vim]', '<Nop>',{ noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>v', '[vim]',{ noremap = false })
vim.api.nvim_set_keymap('n', '[vim]e', ':e ++enc=<CR>',{ noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '[vim]t', ':%retab!<CR>',{ noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '[vim]<CR>', ':set fileformat=unix<CR>',{ noremap = true, silent = true })
vim.api.nvim_set_keymap('i', 'jj', '<ESC>:<C-u>w<CR>',{ noremap = true, silent = true })
