[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  let g:dein#install_github_api_token=$GITHUB_OAUTH_TOKEN
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja.git'
hook_add = '''
    set helplang=ja,en
'''

# Set if use Vim{{{
#    use for remote plugins{{{
[[plugins]]
repo = 'roxma/nvim-yarp'
if='''! has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if='''! has('nvim')'''
#    }}}
# Set easy translate
[[plugins]]
repo = 'skanehira/translate.vim'
if='''!has('nvim')'''
rev = 'v0.0.3'
hook_add = '''
    let g:translate_source = "en"
    let g:translate_target = "ja"
    let g:translate_winsize = 10
    vmap tj <Plug>(VTranslate)
    vmap te <Plug>(VTranslateBang)
'''
# }}}


# Set shortcut commands
[[plugins]]
repo = 'c000/rapidfire.vim'
hook_add = '''
    let g:rapidfire#persistent_filename="~/dotfiles/common/vim/key_setting.json"
    nnoremap <F1>    :<C-u>Rapidfire F1<CR>
    nnoremap <F2>    :<C-u>Rapidfire F2<CR>
    nnoremap <F3>    :<C-u>Rapidfire F3<CR>
    nnoremap <Up>    :<C-u>Rapidfire Up<CR>
    nnoremap <Left>  :<C-u>Rapidfire Left<CR>
    nnoremap <Right> :<C-u>Rapidfire Right<CR>
    nnoremap <Down>  :<C-u>Rapidfire Down<CR>
'''

# Make new Function{{{
# help for f or F
[[plugins]]
repo='unblevable/quick-scope'
hook_add='''
    let g:qs_highlight_on_keys = ['f','F']
'''

#    Easy action motions{{{
# it can easy to maeke "surround"
[[plugins]]
repo = 'tpope/vim-surround'
# it can easy to make "comment"
[[plugins]]
repo = 'tpope/vim-commentary'
# it can easy to repeate command
[[plugins]]
repo = 'tpope/vim-repeat'
#    }}}

#    Easy action commands{{{
# easy to change word
[[plugins]]
repo = 'lambdalisue/reword.vim'

# use for markdown
[[plugins]]
repo = 'godlygeek/tabular'

# It can run and test in vim
[[plugins]]
repo='thinca/vim-quickrun'

# use cheatsheet
[[plugins]]
repo='reireias/vim-cheatsheet'
hook_add = '''
let g:cheatsheet#cheat_file = '~\dotfiles\common\vim\cheatsheet.md'
nmap <Leader>cc :<c-u>Cheat<CR>
'''
#    }}}
# }}}

# To use git in vim{{{
[[plugins]]
repo = 'tpope/vim-fugitive'

# Check git diff in numberline
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add='''
    set signcolumn=yes
    let g:gitgutter_map_keys = 0
    nnoremap [Git] <Nop>
    nmap <Leader>g [Git]
    nmap [Git]p <Plug>(GitGutterPrevHunk)
    nmap [Git]n <Plug>(GitGutterNextHunk)
    nmap [Git]a <Plug>(GitGutterStageHunk)
    nmap [Git]u <Plug>(GitGutterRevertHunk)
    nmap [Git]v <Plug>(GitGutterPreviewHunk)
'''
# }}}

[[plugins]]
repo='twitvim/twitvim'
if='''0'''
hook_add='''
    source ~\dotfiles\twitkeys.vim
    map <Leader>t [Twit]
    noremap [Twit]t :<C-u>PosttoTwitter<CR>
    noremap [Twit]f :<C-u>FriendsTwitter<CR>
    noremap [Twit]u :<C-u>UserTwitter<CR>
    noremap [Twit]r :<C-u>MentionsTwitter<CR>
    noremap [Twit]d :<C-u>DMTwitter<CR>
    noremap [Twit]s :<C-u>DMSentTwitter<CR>
    noremap [Twit]n :<C-u>NextTwitter<CR>
    nnoremap [Twit]p :<C-u>PreviousTwitter<CR>
    nnoremap <Leader><Leader> :<C-u>RefreshTwitter<CR>
'''

[[plugins]]
repo = 'skanehira/code2img.vim'
hook_add = '''
let g:code2img_theme = 'monokai'
let g:code2img_line_number = 1
'''

# Set looks{{{

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# Make indentline
[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = ['IndentLinesToggle']
hook_add = '''
    let g:loaded_indentLine = 1
'''

#    Colorschemes{{{
[[plugins]]
repo = 'patstockwell/vim-monokai-tasty'
hook_add = '''
let g:vim_monokai_tasty_italic = 1
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo='tomasr/molokai'
#    }}}
# }}}
