[[plugins]]
repo='Shougo/ddu.vim'
depends='denops.vim'
hook_source='''
" You must set the default ui in the first
call ddu#custom#patch_global({
    \ 'ui': 'std',
    \ })

" Specify matcher.
call ddu#custom#patch_global({
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \   }
    \ })

" Set default sources
"call ddu#custom#patch_global({
"    \ 'sources': [{'name': 'file', 'params': {}}],
"    \ })

" Call default sources
"call ddu#start({})

" Set name specific configuration
"call ddu#custom#patch_local('files', {
"    \ 'sources': [
"    \   {'name': 'file', 'params': {}},
"    \   {'name': 'file_old', 'params': {}},
"    \ ],
"    \ })

" Specify name
"call ddu#start({'name': 'files'})

" Specify source with params
"call ddu#start([{'name': 'file_rec', 'params': {'path': expand('~')}}])
'''
[plugins.ftplugin]
ddu-std='''
nnoremap <buffer><silent> <CR>
\ <Cmd>call ddu#ui#std#do_map('doAction')<CR>
nnoremap <buffer><silent> <Space>
\ <Cmd>call ddu#ui#std#do_map('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
\ <Cmd>call ddu#ui#std#do_map('openFilterWindow')<CR>
nnoremap <buffer><silent> q
\ <Cmd>call ddu#ui#std#do_map('quit')<CR>
'''
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'
